### PR TITLE
Support for all MC languages + better .gitignore

### PR DESCRIPTION
**Pull request by ghost**
I recently implemented something similar in my mod and since this is on the official fabric wiki it would be cool if it supported all languages, so here we go. I left custom MC languages commented as Crowdin does no have those predefined. Also while at it I updated .gitignore aswell.

### CODE REVIEW

**Comment by gbl** [comment]
This is great, thank you a lot!

Before publishing, I'll rework it a bit though. The problem is, I don't want to require people to provide mainly identical translations for all variants of `es`; instead, if there's a `es-ES` translation, it should go to all `es-??` files, unless there's an override for a specific variant on Crowdin. Likewise, the `de` translation should go to `de_de`, `de_ch` and `de_at`, so you don't *have* to maintain all three unless someone explicitly wants to.

Also, you have a typo, you generate `en_au` from `de-AT`. Going to fix this, but if you're using the same table in your project, maybe it also needs fixing there.

**Comment by ghost** [comment]
Ahh, I see what you mean since you are mapping it the other way around. In my project I map the Crowdin code to MC code. Also thanks for the typo must have missed that one.

EDIT: but still I think the languages should stay regardless since they are 1:1 mapped to what's on crowdin and people don't generally expect a single language be present in it's other more specific forms (ex. like having the english translation be available in australian english, which I think should not be the case).

**Comment by gbl** [comment]
I agree that the languages should stay regardless.
That's why, In my previous version, I had stuff like 
```
         add("es_es", "es-ES");
         add("es_mx", "es-ES");
         add("es_uy", "es-ES");
         add("es_ve", "es-ES");
```
(and several more); the single crowdin language `es-ES` got mapped into the 7 different language files for all countries. With your complete map, which says for example `add("es_ve", "es-VE");`, I need an `es-VE` translation maintained on Crowdin. This might be ok in some cases where someone volunteers to maintain each country separately (I had someone ask me if I could add `pt_br` because it's quite different from `pt_pt` and they wanted to do them differently), 

So what I want to do is something like `add("es_ve", "es-VE,es-ES")` to mean generate the MC `es_ve.json` from crowdin `es-VE` if it exists, and from  `es-ES`  if no `es-VE`  exists. This will, obviously, require rewriting some code. Or, to stay with your example, do something like `add("en_au", "en-AU,en")` so a `en_au.json` will be generated in any case, but from the general `en` crowdin translation if no `en-AU` exists there.

**Comment by ghost** [comment]
I still don't think it's worth it tho, becouse if someone wants to use let's say East Franconian (or any other german variations), they don't want to see regular german language or atleast I think they don't. They would expect to see the specific language or the default lang.

**Comment by gbl** [comment]
Certainly not in the east franconian version, but if someone has their MC on de_AT, the de_de version will make them happier than English. And if someone sets their MC to es_VE, the es_es version will be more readable than English to them as well. es_AU is a bit of a special case as the "default" is English anyway.

**Comment by ghost** [comment]
I mean yeah, in some cases it makes sense, expecially with a lot of spanish versions as those are fairly similar. But you would need to handpick those that are this similar and it might not be worth the effort.

Also if someone wants a specific spanish version and it's not available they might try the `es_es` or check the mod for it's available languages, on the other hand both approaches work, but for me personally I would be confused if I saw a different language that expected. Maybe an option that would allow the translation downloader to choose if it should be strict or group the languages together.

**Pull request merged**
